apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app.kubernetes.io/name:my-java-spring-boot
  name: my-java-spring-boot
spec:
  output:
    to:
      kind: DockerImage
      name: docker.io/appa253/my-java-spring-boot:latest
  source:
    # Expect a local directory to be streamed to OpenShift as a build source
    type: Binary
    binary: {}
  strategy:
    type: Docker
    dockerStrategy:
      # Find the image build instructions in ./Dockerfile
      dockerfilePath: Dockerfile
